[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --accept-data-loss"]

[start]
cmd = "node index.js"

[variables]
NODE_ENV = "production"

# Force backend detection
[providers]
node = true
