-- CreateTable site_config
CREATE TABLE "site_config" (
    "id" TEXT NOT NULL,
    "site_name" TEXT NOT NULL DEFAULT 'Opillia Shop',
    "site_description" TEXT NOT NULL DEFAULT 'Найкращі напої та делікатеси з доставкою по Києву',
    "logo_url" TEXT NOT NULL DEFAULT '/logo.png',
    "favicon_url" TEXT NOT NULL DEFAULT '/favicon.ico',
    "seo_title" TEXT NOT NULL DEFAULT 'Opillia Shop - Найкращі напої та делікатеси',
    "seo_description" TEXT NOT NULL DEFAULT 'Замовляйте найкращі напої, сири, м''ясо та делікатеси з доставкою по Києву',
    "seo_keywords" TEXT NOT NULL DEFAULT 'напої, сир, м''ясо, делікатеси, доставка, Київ',
    "og_image_url" TEXT NOT NULL DEFAULT '/og-image.jpg',
    "homepage_type" TEXT NOT NULL DEFAULT 'landing',
    "hero_title" TEXT NOT NULL DEFAULT 'Найкращі напої та делікатеси',
    "hero_subtitle" TEXT NOT NULL DEFAULT 'Швидка доставка свіжих продуктів по Києву',
    "hero_banner_url" TEXT NOT NULL DEFAULT '/hero-banner.jpg',
    "hero_cta_text" TEXT NOT NULL DEFAULT 'Почати покупки',
    "company_name" TEXT NOT NULL DEFAULT 'ТОВ "Опілля Шоп"',
    "company_address" TEXT NOT NULL DEFAULT 'вул. Хрещатик, 1, Київ, 01001',
    "company_phone" TEXT NOT NULL DEFAULT '+38 (097) 324 46 68',
    "company_email" TEXT NOT NULL DEFAULT 'info@opillia.com.ua',
    "company_website" TEXT NOT NULL DEFAULT 'https://opillia.com.ua',
    "facebook_url" TEXT,
    "instagram_url" TEXT,
    "telegram_url" TEXT,
    "viber_url" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'UAH',
    "timezone" TEXT NOT NULL DEFAULT 'Europe/Kiev',
    "language" TEXT NOT NULL DEFAULT 'uk',
    "min_order_amount" DOUBLE PRECISION NOT NULL DEFAULT 300,
    "delivery_base_fee" DOUBLE PRECISION NOT NULL DEFAULT 99,
    "delivery_base_distance_km" DOUBLE PRECISION NOT NULL DEFAULT 2,
    "delivery_extra_fee_per_km" DOUBLE PRECISION NOT NULL DEFAULT 30,
    "free_delivery_threshold" DOUBLE PRECISION NOT NULL DEFAULT 1000,
    "enable_reviews" BOOLEAN NOT NULL DEFAULT true,
    "enable_untappd" BOOLEAN NOT NULL DEFAULT true,
    "enable_likes" BOOLEAN NOT NULL DEFAULT true,
    "enable_ai_chat" BOOLEAN NOT NULL DEFAULT true,
    "enable_recommendations" BOOLEAN NOT NULL DEFAULT true,
    "enable_notifications" BOOLEAN NOT NULL DEFAULT true,
    "enable_dark_mode" BOOLEAN NOT NULL DEFAULT true,
    "enable_online_payment" BOOLEAN NOT NULL DEFAULT false,
    "wayforpay_merchant_account" TEXT NOT NULL DEFAULT '',
    "wayforpay_merchant_secret" TEXT NOT NULL DEFAULT '',
    "wayforpay_merchant_domain" TEXT NOT NULL DEFAULT 'opillia.com.ua',
    "wayforpay_test_mode" BOOLEAN NOT NULL DEFAULT true,
    "primary_color" TEXT NOT NULL DEFAULT '#2563eb',
    "secondary_color" TEXT NOT NULL DEFAULT '#64748b',
    "accent_color" TEXT NOT NULL DEFAULT '#f59e0b',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "site_config_pkey" PRIMARY KEY ("id")
);

